import {
    AlertCircle,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowLeft,
    ArrowLeftRight,
    ArrowUp,
    ArrowUpRight,
    Building,
    Building2,
    Calendar,
    CalendarCheck,
    Car,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CreditCard,
    DoorOpen,
    Download,
    Eye,
    FileText,
    Filter,
    Folder,
    Home,
    Image,
    KeyRound,
    LayoutDashboard,
    LogOut,
    type LucideIcon,
    Mail,
    Menu,
    Minus,
    Package,
    Pencil,
    Phone,
    PiggyBank,
    Plus,
    Receipt,
    Search,
    Settings,
    ShieldCheck,
    SlidersHorizontal,
    Sparkles,
    Store,
    Tag,
    Tags,
    Trash2,
    TrendingDown,
    TrendingUp,
    Upload,
    UploadCloud,
    User,
    UserX,
    Wallet,
    X,
} from 'lucide-react';
import type { ComponentProps } from 'react';

/** Maps the kebab-case icon names used across the data to lucide components. */
const ICONS: Record<string, LucideIcon> = {
    'alert-circle': AlertCircle,
    'arrow-down-left': ArrowDownLeft,
    'arrow-down-right': ArrowDownRight,
    'arrow-left': ArrowLeft,
    'arrow-left-right': ArrowLeftRight,
    'arrow-up': ArrowUp,
    'arrow-up-right': ArrowUpRight,
    building: Building,
    'building-2': Building2,
    calendar: Calendar,
    'calendar-check': CalendarCheck,
    car: Car,
    check: Check,
    'check-circle-2': CheckCircle2,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    'credit-card': CreditCard,
    'door-open': DoorOpen,
    download: Download,
    eye: Eye,
    'file-text': FileText,
    filter: Filter,
    folder: Folder,
    home: Home,
    image: Image,
    'key-round': KeyRound,
    'layout-dashboard': LayoutDashboard,
    'log-out': LogOut,
    mail: Mail,
    menu: Menu,
    minus: Minus,
    package: Package,
    pencil: Pencil,
    phone: Phone,
    'piggy-bank': PiggyBank,
    plus: Plus,
    receipt: Receipt,
    search: Search,
    settings: Settings,
    'shield-check': ShieldCheck,
    'sliders-horizontal': SlidersHorizontal,
    sparkles: Sparkles,
    store: Store,
    tag: Tag,
    tags: Tags,
    'trash-2': Trash2,
    'trending-down': TrendingDown,
    'trending-up': TrendingUp,
    upload: Upload,
    'upload-cloud': UploadCloud,
    user: User,
    'user-x': UserX,
    wallet: Wallet,
    x: X,
};

interface IconProps extends ComponentProps<LucideIcon> {
    name: string;
}

export function Icon({ name, ...props }: IconProps) {
    const LucideComponent = ICONS[name] ?? Home;
    return <LucideComponent {...props} />;
}
